"""empty message

Revision ID: 0502def5fd5b
Revises:
Create Date: 2026-01-20 10:56:55.704172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0502def5fd5b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="recipe",
    )
    op.create_index(
        op.f("ix_recipe_ingredients_id"),
        "ingredients",
        ["id"],
        unique=False,
        schema="recipe",
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("mail", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("mail"),
        schema="recipe",
    )
    op.create_index(
        op.f("ix_recipe_profiles_user_id"),
        "profiles",
        ["user_id"],
        unique=True,
        schema="recipe",
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="recipe",
    )
    op.create_index(
        op.f("ix_recipe_tags_category"),
        "tags",
        ["category"],
        unique=False,
        schema="recipe",
    )
    op.create_index(
        op.f("ix_recipe_tags_id"),
        "tags",
        ["id"],
        unique=False,
        schema="recipe",
    )
    op.create_index(
        op.f("ix_recipe_tags_name"),
        "tags",
        ["name"],
        unique=True,
        schema="recipe",
    )
    op.create_index(
        op.f("ix_recipe_tags_slug"),
        "tags",
        ["slug"],
        unique=True,
        schema="recipe",
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("profile_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["recipe.profiles.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="recipe",
    )
    op.create_index(
        op.f("ix_recipe_recipes_id"),
        "recipes",
        ["id"],
        unique=False,
        schema="recipe",
    )
    op.create_index(
        op.f("ix_recipe_recipes_profile_id"),
        "recipes",
        ["profile_id"],
        unique=False,
        schema="recipe",
    )
    op.create_table(
        "favorites",
        sa.Column("profile_id", sa.BigInteger(), nullable=False),
        sa.Column("recipe_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "order_index",
            sa.Integer(),
            nullable=False,
            comment="Порядок рецептов в избранном",
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
            comment="Заметки пользователя к рецепту в избранном",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["recipe.profiles.user_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipe.recipes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_id", "recipe_id"),
        schema="recipe",
    )
    op.create_index(
        op.f("ix_recipe_favorites_profile_id"),
        "favorites",
        ["profile_id"],
        unique=False,
        schema="recipe",
    )
    op.create_index(
        op.f("ix_recipe_favorites_recipe_id"),
        "favorites",
        ["recipe_id"],
        unique=False,
        schema="recipe",
    )
    op.create_table(
        "recipe_ingredients",
        sa.Column("recipe_id", sa.BigInteger(), nullable=False),
        sa.Column("ingredient_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "quantity",
            sa.Numeric(precision=10, scale=3),
            nullable=True,
            comment="Количество ингредиента",
        ),
        sa.Column(
            "unit",
            sa.String(length=20),
            nullable=True,
            comment="Единица измерения (г, мл, шт, ст.л., ч.л. и т.д.)",
        ),
        sa.Column(
            "order",
            sa.Integer(),
            nullable=True,
            comment="Порядок ингредиентов в рецепте",
        ),
        sa.Column(
            "preparation_note",
            sa.String(length=200),
            nullable=True,
            comment="Способ подготовки (нарезать, натереть и т.д.)",
        ),
        sa.Column(
            "is_optional",
            sa.Boolean(),
            nullable=False,
            comment="Обязательный или опциональный ингредиент",
        ),
        sa.Column(
            "group",
            sa.String(length=50),
            nullable=True,
            comment="Группа (для соуса, маринада, украшения)",
        ),
        sa.Column(
            "state",
            sa.String(length=30),
            nullable=True,
            comment="Состояние ингредиента",
        ),
        sa.Column(
            "temperature",
            sa.String(length=30),
            nullable=True,
            comment="Температура ингредиента",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"], ["recipe.ingredients.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipe.recipes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("recipe_id", "ingredient_id"),
        schema="recipe",
    )
    op.create_table(
        "recipe_tags",
        sa.Column("recipe_id", sa.BigInteger(), nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.Column("added_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["added_by"], ["recipe.profiles.user_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipe.recipes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["recipe.tags.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("recipe_id", "tag_id"),
        schema="recipe",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_tags", schema="recipe")
    op.drop_table("recipe_ingredients", schema="recipe")
    op.drop_index(
        op.f("ix_recipe_favorites_recipe_id"),
        table_name="favorites",
        schema="recipe",
    )
    op.drop_index(
        op.f("ix_recipe_favorites_profile_id"),
        table_name="favorites",
        schema="recipe",
    )
    op.drop_table("favorites", schema="recipe")
    op.drop_index(
        op.f("ix_recipe_recipes_profile_id"),
        table_name="recipes",
        schema="recipe",
    )
    op.drop_index(
        op.f("ix_recipe_recipes_id"), table_name="recipes", schema="recipe"
    )
    op.drop_table("recipes", schema="recipe")
    op.drop_index(
        op.f("ix_recipe_tags_slug"), table_name="tags", schema="recipe"
    )
    op.drop_index(
        op.f("ix_recipe_tags_name"), table_name="tags", schema="recipe"
    )
    op.drop_index(
        op.f("ix_recipe_tags_id"), table_name="tags", schema="recipe"
    )
    op.drop_index(
        op.f("ix_recipe_tags_category"), table_name="tags", schema="recipe"
    )
    op.drop_table("tags", schema="recipe")
    op.drop_index(
        op.f("ix_recipe_profiles_user_id"),
        table_name="profiles",
        schema="recipe",
    )
    op.drop_table("profiles", schema="recipe")
    op.drop_index(
        op.f("ix_recipe_ingredients_id"),
        table_name="ingredients",
        schema="recipe",
    )
    op.drop_table("ingredients", schema="recipe")
    # ### end Alembic commands ###
