"""empty message

Revision ID: 4ab2bdf87545
Revises: 
Create Date: 2026-01-10 20:07:15.007332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab2bdf87545'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='recipe'
    )
    op.create_index(op.f('ix_recipe_ingredients_id'), 'ingredients', ['id'], unique=False, schema='recipe')
    op.create_table('user_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='recipe'
    )
    op.create_index(op.f('ix_recipe_user_profiles_id'), 'user_profiles', ['id'], unique=False, schema='recipe')
    op.create_index(op.f('ix_recipe_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True, schema='recipe')
    op.create_table('recipes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['recipe.user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='recipe'
    )
    op.create_index(op.f('ix_recipe_recipes_id'), 'recipes', ['id'], unique=False, schema='recipe')
    op.create_index(op.f('ix_recipe_recipes_profile_id'), 'recipes', ['profile_id'], unique=False, schema='recipe')
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True, comment='Количество ингредиента'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='Единица измерения (г, мл, шт, ст.л., ч.л. и т.д.)'),
    sa.Column('order', sa.Integer(), nullable=True, comment='Порядок ингредиентов в рецепте'),
    sa.Column('preparation_note', sa.String(length=200), nullable=True, comment='Способ подготовки (нарезать, натереть и т.д.)'),
    sa.Column('is_optional', sa.Boolean(), nullable=False, comment='Обязательный или опциональный ингредиент'),
    sa.Column('group', sa.String(length=50), nullable=True, comment='Группа (для соуса, маринада, украшения)'),
    sa.Column('state', sa.String(length=30), nullable=True, comment='Состояние ингредиента'),
    sa.Column('temperature', sa.String(length=30), nullable=True, comment='Температура ингредиента'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['recipe.ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='recipe'
    )
    op.create_index(op.f('ix_recipe_recipe_ingredients_id'), 'recipe_ingredients', ['id'], unique=False, schema='recipe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_recipe_ingredients_id'), table_name='recipe_ingredients', schema='recipe')
    op.drop_table('recipe_ingredients', schema='recipe')
    op.drop_index(op.f('ix_recipe_recipes_profile_id'), table_name='recipes', schema='recipe')
    op.drop_index(op.f('ix_recipe_recipes_id'), table_name='recipes', schema='recipe')
    op.drop_table('recipes', schema='recipe')
    op.drop_index(op.f('ix_recipe_user_profiles_user_id'), table_name='user_profiles', schema='recipe')
    op.drop_index(op.f('ix_recipe_user_profiles_id'), table_name='user_profiles', schema='recipe')
    op.drop_table('user_profiles', schema='recipe')
    op.drop_index(op.f('ix_recipe_ingredients_id'), table_name='ingredients', schema='recipe')
    op.drop_table('ingredients', schema='recipe')
    # ### end Alembic commands ###
