# кароче как это работает 
# все запросы к нашему приложению приходят сюда 
# nginx это точка входа Apigetway если по научному
# вот запрос пришел он смотрит приватный он или нет (ниже обьявлен список публичных маршрутов все остаьные по умолчанию приватные
# почеему так а потомучто если при разработке мы случайнотне добавим публичный маршрут в наш белый список ничеого критичного не 
# прозойдет) дальше взависимости от резкльтата проверки запрос перенаправляеться на внутренние локации /public || /private в приватном 
# отправляем подзапрос который также перекидывает на внутренний маршрут проверки токен и там идет внешнее проксирование в 
# наш сервис авторизации он проверяет токен ели все ок подзапрос возвращает 200 и user_id в заголовках в придачу мы модифицируем запрос
# и наконецто он идет в целевой сервис с публичным маршуртом проще он сразу отправляет запрос в целевой сервис



events {
    worker_connections 1024; # максимальное колличество подключений 
}


# HTTP 
http {

    # Структуа предназначена для храненния публичных маршрутов 
    # это достаточно удобно нам не нужно в каждом сервисе писать middleware для авторизации 
    # можно просто добавлять ендпоинты в каждый сервис а на уровне nginx решать приватный он или нет 
    map $uri $is_public {
        default 0;

        ~*^/api/v[0-9]+/auth/login 1;
        ~*^/api/v[0-9]+/auth/register 1;
        ~*^/api/v[0-9]+/auth/refresh 1;
        
        # Публичные системные маршруты
        ~*^/api/v[0-9]+/test 1;
        ~*^/api/v[0-9]+/health 1;
        ~*^/api/v[0-9]+/docs 1;
        ~*^/api/v[0-9]+/openapi\.json 1;
        ~*^/api/v[0-9]+/swagger 1;
        ~*^/api/v[0-9]+/redoc 1;
    }
    

    # Блок UP stream 
    # Работаем внутри доекра поэтому указываем имена докер контейнеров в его внутреней DNS сети 
    upstream auth-service {
        server auth-service:8001;
    }

    upstream recipe-service{
        server recipe-service:8002;
    }

    proxy_set_header Host $host; # имя хоста на который пользователь отправил запрос
    proxy_set_header X-Real-IP $remote_addr; # Ip клиента 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # цепочка проксирования 
    proxy_set_header X-Forwarded-Proto $scheme; # реальный протокол 

    # Блок Server
    server {
        listen 80; #
        server_name 127.0.0.1; 

         location = /health {
            add_header Content-Type application/json;
            return 200 '{"status": "healthy", "timestamp": "$time_iso8601"}';
        }



        location = /auth {
            internal; 
            proxy_method POST;
            proxy_pass http://auth-service/api/v1/auth/authorized;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
        }

        location = /private {
            internal;

            auth_request /auth;
            auth_request_set $user_id $upstream_http_x_user_id;
            proxy_set_header X-User-Id $user_id;

            proxy_pass http://recipe-service$request_uri;
        }

        location = /public {
            internal;
            proxy_pass http://auth-service$request_uri;
        }

        location /api/ {
            if ($is_public = 1) {
                rewrite ^ /public last;
            }   
            rewrite ^ /private last;
        }
       
        location @error401 {
            add_header Content-Type application/json;
            add_header WWW-Authenticate 'Bearer realm="API", error="invalid_token"';
            return 401 '{"error": "Unauthorized", "code": "AUTH_001", "message": "Invalid or missing authentication token", "timestamp": "$time_iso8601"}';
        }

        location @error403 {
            add_header Content-Type application/json;
            return 403 '{"error": "Forbidden", "code": "AUTH_002", "message": "Insufficient permissions", "timestamp": "$time_iso8601"}';
        }
    }
}