"""empty message

Revision ID: 319b2c34c608
Revises:
Create Date: 2026-01-19 15:36:19.100216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "319b2c34c608"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("mail", sa.String(), nullable=True),
        sa.Column("hash_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mail"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_users_id"), "users", ["id"], unique=False, schema="auth"
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("device_name", sa.String(), nullable=False),
        sa.Column("ip_addres", sa.String(), nullable=False),
        sa.Column("refresh_jti", sa.UUID(), nullable=False),
        sa.Column("last_activity", sa.DateTime(), nullable=False),
        sa.Column("is_block", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["auth.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_id"),
        "user_sessions",
        ["id"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_refresh_jti"),
        "user_sessions",
        ["refresh_jti"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_user_id"),
        "user_sessions",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_auth_user_sessions_user_id"),
        table_name="user_sessions",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_user_sessions_refresh_jti"),
        table_name="user_sessions",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_user_sessions_id"),
        table_name="user_sessions",
        schema="auth",
    )
    op.drop_table("user_sessions", schema="auth")
    op.drop_index(op.f("ix_auth_users_id"), table_name="users", schema="auth")
    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
